version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: paopao
      POSTGRES_USER: paopao
      POSTGRES_PASSWORD: paopao
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./scripts/migration/postgres:/docker-entrypoint-initdb.d
      - ./custom/data/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    command: postgres -c shared_buffers=256MB -c effective_cache_size=512MB -c maintenance_work_mem=64MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100
    networks:
      - paopao-network

  # minio:
  #   image: bitnami/minio:latest
  #   restart: always
  #   environment:
  #     MINIO_ROOT_USER: minio-root-user
  #     MINIO_ROOT_PASSWORD: minio-root-password
  #     MINIO_DEFAULT_BUCKETS: paopao:public
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   volumes:
  #     - ./custom/data/minio/data:/data
  #   networks:
  #     - paopao-network

  # redis:
  #   image: redis:${REDIS_TAG:-7.2.1-alpine}
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - paopao-network

  redis:
    image: redis/redis-stack:${REDIS_STACK_TAG:-7.2.0-v6}
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDISEARCH_ARGS: "MAXSEARCHRESULTS 5"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    command: redis-server --maxmemory 400mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    networks:
      - paopao-network
  
  # zinc:
  #   image: bitbus/zincsearch:latest
  #   user: zincsearch
  #   restart: always
  #   ports:
  #     - 4080:4080
  #   volumes:
  #     - ./custom/data/zinc/data:/data
  #   environment:
  #     ZINC_FIRST_ADMIN_USER: admin
  #     ZINC_FIRST_ADMIN_PASSWORD: admin
  #     DATA_PATH: /data
  #   networks:
  #     - paopao-network

  meili:
    image: getmeili/meilisearch:${MEILI_TAG:-v1.7}
    restart: always
    ports:
      - 7700:7700
    volumes:
      - ./custom/data/meili/data:/meili_data
    environment:
      - MEILI_MASTER_KEY=paopao-meilisearch
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - paopao-network

  gorush:
    image: appleboy/gorush:latest
    restart: always
    ports:
      - 8088:8088
    volumes:
      - ./gorush-config.yml:/etc/gorush/config.yml
      - ./custom/gorush:/etc/gorush
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      - redis
    networks:
      - paopao-network

  # meilisearch-ui:
  #   image: riccoxie/meilisearch-ui:latest
  #   restart: always
  #   ports:
  #     - 24900:24900
  #   networks:
  #     - paopao-network
  
  # openobserve:
  #   image: public.ecr.aws/zinclabs/openobserve:${OPENOBSERVE_TAG:-latest}
  #   restart: always
  #   ports:
  #     - 5080:5080
  #   volumes:
  #     - ./custom/data/openobserve/data:/data
  #   environment:
  #     ZO_DATA_DIR: /data
  #     ZO_ROOT_USER_EMAIL: root@paopao.info
  #     ZO_ROOT_USER_PASSWORD: paopao-ce
  #   networks:
  #     - paopao-network

  # pyroscope:
  #   image: pyroscope/pyroscope:${PYROSCOPE_TAG:-latest}
  #   restart: always
  #   ports:
  #     - 4040:4040
  #   command:
  #     - 'server'
  #   networks:
  #     - paopao-network

  # phpmyadmin:
  #   image: phpmyadmin:${PHPMYADMIN_TAG:-5.2}
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_USER=paopao
  #     - PMA_PASSWORD=paopao
  #   networks:
  #     - paopao-network

  


  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_HOST=backend:8008
        - USE_API_HOST=yes
        - EMBED_UI=no
        - USE_DIST=no
    restart: always
    depends_on:
      - db
      - redis
      - meili
      - gorush
    volumes:
      - ./config.yaml:/app/paopao-ce/config.yaml
      - ./custom:/app/paopao-ce/custom
    ports:
      - 8008:8008
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    networks:
      - paopao-network

networks:
  paopao-network:
      driver: bridge
